namespace NuclearReactorSimulator.Application;

/// <summary>
/// Describes the currently composed application baseline without coupling the UI to build-time constants.
/// </summary>
public sealed record ApplicationDescriptor(string ProductName, string Milestone, string Status)
{
    public static ApplicationDescriptor Current { get; } = new(
        "Nuclear Reactor Simulator",
        "M10.9.4.1-H.19 — Four-Node Long-Horizon & Cross-Profile Qualification",
        "H.19 candidate on the user-validated H.18 Hotfix 1 four-node split-diagnosis baseline — current-v2 production remains on the validated 10 ms ExplicitCommittedState path. H.18 Hotfix 1 validated unchanged H.9 plus unchanged bounded 2% pressure / 5 K hysteresis at steam/stop-out/header/turbine-inlet over all 245 frozen H.17 failures plus 16 deterministic success controls: 261/261 converged, 120/120 turbine-inlet-mismatch failures recovered, 125/125 non-mismatch failures recovered, 16/16 controls preserved, committed selection remained transparent, exact repeat passed and no residual failure or new untargeted branch-disagreement node remained. H.19 returns that exact four-node shadow policy to the complete H.17 long-horizon/cross-profile qualification contract: 30,000 explicit reference intervals across steady-long, validated 5→0→5 MWe load-pulse, condenser-cooling-pulse and combined load+cooling profiles; the unchanged P060/F040 census must reproduce exactly 3,046 trigger intervals, 92 episodes and 473 deterministic representatives whose profile/interval keys match the frozen H.17 evidence. All 473 representatives are evaluated with the unchanged H.9 Jacobian corrector and the unchanged four-node bounded-hysteresis target set. H.19 reports recovery of all 245 H.17 failures, preservation of all 228 H.17 successes, 120,000 committed target phase-state checks, deterministic repeat, closure/ownership, inherited hold/release challenges and all-node candidate-vs-explicit inverse-branch evidence, including both untargeted candidate-only late-shadow and untargeted selected-phase mismatch detection. SimplifiedWaterSteamThermodynamicModel.Resolve(), ThermodynamicBranchContinuityModel behavior, H.9 tolerances, P060/F040, physical coefficients and PlantNetworkOrchestrator remain unchanged. No shadow state is committed; no production hysteresis, branch reorder, active set, semi-smooth solver, trigger retuning, hysteresis-limit retuning, physical coefficient retuning, hidden flow filtering, thermodynamic clamping, wall-clock branching or external timestep change is introduced. Phase H remains open and Phase I remains deferred." );
}
