namespace NuclearReactorSimulator.Application;

/// <summary>
/// Describes the currently composed application candidate without coupling the UI to build-time constants.
/// </summary>
public sealed record ApplicationDescriptor(string ProductName, string Milestone, string Status)
{
    public static ApplicationDescriptor Current { get; } = new(
        "Nuclear Reactor Simulator",
        "M10.9.7.3 Hotfix 2 REV2 — Desktop Host Failure & Session Save Integrity",
        "M10.9.7.3 Hotfix 1 REV2 is VALIDATED after build, complete ordinary tests, focused live-workspace audit and the manual HMI checklist on 2026-08-21. The original Hotfix 2 candidate is SUPERSEDED / NOT VALIDATED because its new asynchronous App tests failed compilation under warnings-as-errors with eight xUnit1051 cancellation-token analyzer violations. Hotfix 2 REV1 is also SUPERSEDED / NOT VALIDATED after the ordinary suite exposed three contract defects: InvalidDataException was omitted from the centralized archive-operation policy, the new-file save path attempted an unnecessary backup cleanup, and the historical M10.9.7.1 archive-boundary regression still asserted the superseded inline catch syntax instead of the centralized policy. Hotfix 2 REV2 is stacked exclusively on Hotfix 1 REV2 VALIDATED plus Docs4. It explicitly classifies InvalidDataException as an expected archive/user-data failure, cleans a backup only after the existing-file replacement was successfully committed, and updates the historical source-contract test to verify the centralized policy while preserving the same user-data failure families. The desktop runtime pump continues to convert expected InvalidOperationException/ArithmeticException numerical-step failures, including OverflowException, into PAUSE plus one operator-visible diagnostic while unknown programming failures remain unhandled. Start-recorded-session and reset/recreate boundaries remain protected by the explicit host classification, while load/restore/save share one archive-operation failure policy. SAVE selects a destination before archive export, requires a local desktop filesystem path for safe replacement, writes a unique temporary sibling, flushes it durably, and only then moves/replaces the destination; NRS no longer truncates the existing archive before a replacement is complete. Cancellation performs no archive export, and write/replace failures preserve the previous destination under the local-filesystem contract with best-effort temporary/backup cleanup. Remaining App gauge-scale and COMPUTER setpoint numbers use the same invariant technical decimal convention as the canonical HMI presentation. MISSION / Mission & Performance, F1-F8/no-F9, challenge/scoring/protection ownership, plant-command authority, physics and archive schema remain unchanged. M10.9.7.4 deterministic timeline/drill-down/replay-equivalence remains next only after this Hotfix 2 REV2 is validated."
    );
}
