namespace NuclearReactorSimulator.Application;

/// <summary>
/// Describes the currently composed application baseline without coupling the UI to build-time constants.
/// </summary>
public sealed record ApplicationDescriptor(string ProductName, string Milestone, string Status)
{
    public static ApplicationDescriptor Current { get; } = new(
        "Nuclear Reactor Simulator",
        "M10.9.4.1-H.18 — Turbine-Inlet Continuity Extension & Residual-Floor Split Diagnosis",
        "H.18 candidate on the user-validated H.17 Hotfix 6 long-horizon/cross-profile diagnostic baseline — current-v2 production remains on the validated 10 ms ExplicitCommittedState path. H.17 Hotfix 6 validated the 30,000-interval four-profile audit infrastructure and showed that the H.16 bounded previous-phase hysteresis policy at steam/stop-out/header does not qualify across the long-horizon representative set: 3,046 P060/F040 trigger intervals form 92 episodes, 473 deterministic representatives were qualified, 228/473 converged and 245/473 exhausted line search. H.17 also discovered an untargeted turbine-inlet branch-disagreement class: 120 of the 245 failures have candidate-vs-explicit turbine-inlet phase mismatch, usually candidate SuperheatedVapor versus explicit SaturatedMixture, while 125 failures have no turbine-inlet phase mismatch. H.18 freezes the validated 473-representative H.17 evidence contract, reconstructs the same steady-long, validated 5→0→5 MWe load-pulse, condenser-cooling-pulse and combined load+cooling reference trajectories, evaluates every one of the 245 H.17 failures plus deterministic success controls, and compares the unchanged H.13 bounded 2% pressure / 5 K hysteresis extended only to steam/stop-out/header/turbine-inlet under the unchanged H.9 Jacobian corrector. Every remaining H.18 failure is then diagnosed for mapped-minus-applied node residual ranking, accepted-iterate residual-floor evidence and candidate-vs-explicit inverse-branch disagreement across all fluid nodes. Turbine-inlet committed-state selection is observed independently for transparency. SimplifiedWaterSteamThermodynamicModel.Resolve(), ThermodynamicBranchContinuityModel behavior, H.9 tolerances, P060/F040, physical coefficients and PlantNetworkOrchestrator remain unchanged. No shadow state is committed; no production hysteresis, branch reorder, active set, semi-smooth solver, trigger retuning, hysteresis-limit retuning, physical coefficient retuning, hidden flow filtering, thermodynamic clamping, wall-clock branching or external timestep change is introduced. Phase H remains open and Phase I remains deferred." );
}
