<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NuclearReactorSimulator.Simulation</RootNamespace>
    <AssemblyName>NuclearReactorSimulator.Simulation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Physics\Fluids\ReferenceData\NRSVR2C4.v1.bin" LogicalName="NuclearReactorSimulator.Simulation.Physics.Fluids.ReferenceData.NRSVR2C4.v1.bin" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuclearReactorSimulator.Domain\NuclearReactorSimulator.Domain.csproj" />
  </ItemGroup>
</Project>
