$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$root=Split-Path -Parent $PSScriptRoot;Set-Location $root;$inv=[Globalization.CultureInfo]::InvariantCulture
function Require-R2([bool]$c,[string]$m){if(-not $c){throw $m}}
function KV([string]$p){Require-R2(Test-Path $p -PathType Leaf) ("Missing file {0}" -f $p);$m=@{};foreach($l0 in [IO.File]::ReadAllLines((Resolve-Path $p))){$l=$l0.TrimStart([char]0xFEFF);$i=$l.IndexOf('=');if($i -gt 0){$m[$l.Substring(0,$i)]=$l.Substring($i+1)}};$m}
function D([string]$s){[double]::Parse($s,$inv)}
function W([string]$p,[string[]]$l){[IO.File]::WriteAllLines($p,$l,(New-Object Text.UTF8Encoding($false)))}
$c=Get-Content 'eng\m10-final-vr2-r2-focused-thermodynamic-reference-topology-qualification1-contract.json' -Raw|ConvertFrom-Json
$a=Join-Path $root ([string]$c.execution.artifact_root).Replace('/','\');Require-R2(Test-Path $a -PathType Container) 'R2 artifact root missing.';Require-R2($env:NRS_M10_FINAL_VR2_R2_QUALIFICATION1_ORDINARY_PASS -eq '1') 'Ordinary Release PASS marker missing.'
$self=@(Import-Csv (Join-Path $a '02-reference-selfcheck.csv'));Require-R2($self.Count -eq 18) 'Reference self-check row count mismatch.';Require-R2(@($self|Where-Object{(D $_.relative_error) -gt 1e-8}).Count -eq 0) 'Reference self-check exceeded 1e-8.'
$vr=@(Import-Csv (Join-Path $a '03-vr2-reference-point-qualification.csv'));Require-R2($vr.Count -eq 40) 'VR2 row count mismatch.';Require-R2(@($vr|Where-Object{$_.inverse_applicable -eq 'true'}).Count -eq 39) 'VR2 inverse count mismatch.';Require-R2(@($vr|Where-Object{$_.inverse_applicable -eq 'true' -and $_.production_resolved -ne 'true'}).Count -eq 0) 'VR2 unresolved state.';Require-R2(@($vr|Where-Object{$_.inverse_applicable -eq 'true' -and $_.phase_matches -ne 'true'}).Count -eq 0) 'VR2 phase mismatch.';Require-R2(@($vr|Where-Object{$_.inverse_applicable -eq 'true' -and $_.is_finite -ne 'true'}).Count -eq 0) 'VR2 non-finite state.'
$ex=@(Import-Csv (Join-Path $a '04-exact-v9-topology-qualification.csv'));Require-R2($ex.Count -eq 360) 'Exact-v9 row count mismatch.';Require-R2(@($ex|Where-Object{$_.production_resolved -ne 'true'}).Count -eq 0) 'Exact-v9 unresolved state.';Require-R2(@($ex|Where-Object{$_.phase_matches -ne 'true'}).Count -eq 0) 'Exact-v9 phase mismatch.';Require-R2(@($ex|Where-Object{$_.is_finite -ne 'true'}).Count -eq 0) 'Exact-v9 non-finite state.'
$se=@(Import-Csv (Join-Path $a '05-seam-topology-continuity.csv'));Require-R2($se.Count -eq 1280) 'Seam row count mismatch.';Require-R2(@($se|Select-Object -ExpandProperty boundary_index -Unique).Count -eq 320) 'Seam boundary count mismatch.';foreach($s in @('R1-SIDE','R4-LIQUID-SIDE','R4-VAPOR-SIDE','R2-SIDE')){Require-R2(@($se|Where-Object{$_.probe_side -eq $s}).Count -eq 320) ("Seam side count mismatch: {0}" -f $s)};Require-R2(@($se|Where-Object{$_.production_resolved -ne 'true'}).Count -eq 0) 'Seam unresolved state.';Require-R2(@($se|Where-Object{$_.phase_matches -ne 'true'}).Count -eq 0) 'Seam phase mismatch.'
$s=KV (Join-Path $a '06-topology-qualification-summary.txt');Require-R2($s['status'] -eq 'PASS-R2-TOPOLOGY-QUALIFICATION') 'Topology summary not PASS.';Require-R2((D $s['reference-selfcheck-max-relative-error']) -le 1e-8) 'Reference selfcheck summary fail.';Require-R2((D $s['reference-corpus-input-max-relative-error']) -le 1e-8) 'Reference corpus reconstruction drift.';Require-R2((D $s['boundary-only-reference-relative-error']) -le 1e-8) 'Boundary reference drift.';Require-R2([int]$s['vr2-unresolved'] -eq 0 -and [int]$s['vr2-phase-mismatch'] -eq 0) 'VR2 summary mismatch.';Require-R2([int]$s['exact-v9-unresolved'] -eq 0 -and [int]$s['exact-v9-phase-mismatch'] -eq 0 -and (D $s['exact-v9-phase-agreement-percent']) -eq 100) 'Exact-v9 summary mismatch.';Require-R2([int]$s['seam-unresolved'] -eq 0 -and [int]$s['seam-phase-mismatch'] -eq 0) 'Seam summary mismatch.';Require-R2((D $s['max-core-pressure-relative-error']) -le .25 -and (D $s['max-core-temperature-relative-kelvin-error']) -le .25) '25% blocking ceiling exceeded.';Require-R2((D $s['max-hot-core-pressure-relative-error']) -le .10) '10% planning target exceeded.';Require-R2((D $s['max-liquid-seam-pressure-jump-mpa']) -le .0005137228525280754) 'Liquid seam pressure ceiling exceeded.';Require-R2((D $s['max-liquid-seam-temperature-jump-c']) -le 3.5596193356468575E-05) 'Liquid seam temperature ceiling exceeded.';Require-R2((D $s['max-vapor-seam-pressure-jump-mpa']) -le .00026625516826150886) 'Vapor seam pressure ceiling exceeded.';Require-R2((D $s['max-vapor-seam-temperature-jump-c']) -le .001903154074568647) 'Vapor seam temperature ceiling exceeded.';Require-R2($s['exact-v9-composition-executed'] -eq 'False' -and $s['hydraulic-long-materiality-executed'] -eq 'False') 'Forbidden R2 execution detected.'
$r=KV (Join-Path $a '07-deterministic-repeat.txt');Require-R2($r['status'] -eq 'PASS-DETERMINISTIC-REPEAT' -and [int]$r['state-comparisons'] -eq 1679 -and [int]$r['repeat-mismatches'] -eq 0) 'Deterministic repeat failed.'
W (Join-Path $a '01-contract-and-provenance.txt') @('status=PASS-R2-EVIDENCE-COMPLETE','gate=R2-FOCUSED-THERMODYNAMIC-REFERENCE-TOPOLOGY-QUALIFICATION1','planning1-returned-adjudication=PASS','production-mode=ReferenceConsistentTabulatedInverseDomain','production-mode-value=2','independent-reference=IAPWS-R7-97-2012-REGIONS-1-2-4','c4-is-physical-oracle=False','ordinary-release-suite=PASS','production-src-change=False','historical-tests-change=False','default-activation=False','exact-v9-composition=False','r3-planning-authorized-now=False')
W (Join-Path $a '08-r2-qualification-summary.txt') @('status=PASS-R2-FOCUSED-THERMODYNAMIC-REFERENCE-TOPOLOGY-QUALIFIED','classification=PASS-R2-FOCUSED-THERMODYNAMIC-REFERENCE-TOPOLOGY-QUALIFIED','ordinary-release-suite=PASS',('reference-selfcheck-max-relative-error='+$s['reference-selfcheck-max-relative-error']),('vr2-unresolved='+$s['vr2-unresolved']),('vr2-phase-mismatch='+$s['vr2-phase-mismatch']),('exact-v9-unresolved='+$s['exact-v9-unresolved']),('exact-v9-phase-mismatch='+$s['exact-v9-phase-mismatch']),('exact-v9-phase-agreement-percent='+$s['exact-v9-phase-agreement-percent']),('seam-unresolved='+$s['seam-unresolved']),('seam-phase-mismatch='+$s['seam-phase-mismatch']),('max-core-pressure-relative-error='+$s['max-core-pressure-relative-error']),('max-core-temperature-relative-kelvin-error='+$s['max-core-temperature-relative-kelvin-error']),('max-hot-core-pressure-relative-error='+$s['max-hot-core-pressure-relative-error']),('max-liquid-seam-pressure-jump-mpa='+$s['max-liquid-seam-pressure-jump-mpa']),('max-liquid-seam-temperature-jump-c='+$s['max-liquid-seam-temperature-jump-c']),('max-vapor-seam-pressure-jump-mpa='+$s['max-vapor-seam-pressure-jump-mpa']),('max-vapor-seam-temperature-jump-c='+$s['max-vapor-seam-temperature-jump-c']),'deterministic-repeat=True','r3-planning-authorized-now=False','next-action=RETURN-COMPLETE-R2-EVIDENCE-FOR-ADJUDICATION')
W (Join-Path $a '09-prequalification-review.txt') @('status=R2-PREQUALIFICATION-REVIEW-PASS','finding-1=INDEPENDENT-IF97-REFERENCE-SELFCHECK-PASS','finding-2=MODE2-RESOLVES-ALL-39-VR2-INVERSE-ROWS','finding-3=VR2-PHASE-MISMATCH-ZERO','finding-4=EXACT-V9-360-OF-360-RESOLVED-100PCT-PHASE-AGREEMENT','finding-5=SEAM-1280-OF-1280-RESOLVED-ZERO-PHASE-MISMATCH','finding-6=25PCT-BLOCKING-CEILING-MET','finding-7=10PCT-PLANNING-PRESSURE-TARGET-MET','finding-8=SEAM-CONTINUITY-NONREGRESSION-CEILINGS-MET','finding-9=DETERMINISTIC-REPEAT-PASS','finding-10=ORDINARY-RELEASE-PASS','default-activation-authorized=False','exact-v9-activation-authorized=False','r3-planning-authorized=False','returned-r2-adjudication-required=True')
$files=@(Get-ChildItem $a -File);Require-R2($files.Count -eq 9) 'R2 evidence set must contain exactly nine files.'
Write-Host 'R2 focused thermodynamic/reference/topology qualification adjudication: PASS' -ForegroundColor Green
