using NuclearReactorSimulator.Domain.Physics.Fluids;
using NuclearReactorSimulator.Domain.Physics.Quantities;

namespace NuclearReactorSimulator.Simulation.Physics.Fluids;

/// <summary>
/// Instantaneous result for a simplified centrifugal pump composed with a passive hydraulic path.
/// Positive flow is from the pump path's reference from-node toward its to-node.
/// </summary>
public sealed record PumpFlowResult
{
    internal PumpFlowResult(
        PumpSpeed effectiveSpeed,
        PressureDifference nodePressureDifference,
        PressureDifference activePressureBoost,
        PressureDifference internalPressureLoss,
        PipeFlowResult hydraulicFlow,
        VolumetricFlowRate volumetricFlowRate,
        Power hydraulicPowerExchange,
        Power shaftPowerDemand,
        FluidNodeBalance fromNodeBalance,
        FluidNodeBalance toNodeBalance)
    {
        EffectiveSpeed = effectiveSpeed;
        NodePressureDifference = nodePressureDifference;
        ActivePressureBoost = activePressureBoost;
        InternalPressureLoss = internalPressureLoss;
        HydraulicFlow = hydraulicFlow;
        VolumetricFlowRate = volumetricFlowRate;
        HydraulicPowerExchange = hydraulicPowerExchange;
        ShaftPowerDemand = shaftPowerDemand;
        FromNodeBalance = fromNodeBalance;
        ToNodeBalance = toNodeBalance;
    }

    public PumpSpeed EffectiveSpeed { get; }

    public PressureDifference NodePressureDifference { get; }

    /// <summary>
    /// Ideal active pressure source generated by rotation. It follows the speed-squared affinity law.
    /// </summary>
    public PressureDifference ActivePressureBoost { get; }

    /// <summary>
    /// Signed quadratic pressure loss across the pump's internal hydraulic resistance.
    /// </summary>
    public PressureDifference InternalPressureLoss { get; }

    public PressureDifference NetPumpPressureContribution => ActivePressureBoost - InternalPressureLoss;

    public PipeFlowResult HydraulicFlow { get; }

    public MassFlowRate MassFlowRate => HydraulicFlow.MassFlowRate;

    public VolumetricFlowRate VolumetricFlowRate { get; }

    public Power InternalEnergyFlowRate => HydraulicFlow.InternalEnergyFlowRate;

    /// <summary>
    /// Signed work rate exchanged by the active pump pressure source with the fluid.
    /// Positive means energy is supplied to the fluid; negative means reverse flow drives the source.
    /// </summary>
    public Power HydraulicPowerExchange { get; }

    /// <summary>
    /// Non-regenerative shaft demand for positive hydraulic work. Negative hydraulic exchange does not
    /// create electrical/mechanical generation in this simplified milestone.
    /// </summary>
    public Power ShaftPowerDemand { get; }

    public FluidNodeBalance FromNodeBalance { get; }

    public FluidNodeBalance ToNodeBalance { get; }
}
